name = input("Enter Your Name: ")
print(name)
surname = input("Enter Your Surname: ")
print(surname)
age = int(input("Enter Your Age: "))
print(age)
number1 = int(input("Enter Random Number: "))
print(number1)
number2 = int(input("Enter Random Number Again: "))
print(number2)

print(type(name))
print(type(surname))
print(type(age))
print(type(number1))
print(type(number2))